AWSTemplateFormatVersion: "2010-09-09"

Description: "This is a simple network architecture"

Resources:
    InternetGateway:
        Type: AWS::EC2::InternetGateway
    # Total addresses: 64
    # Network address: 172.16.0.0
    # Broadcast: 172.16.0.64
    # Netmask: /26
    PrivateVpc:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 172.16.0.0/26
            EnableDnsHostnames: false
            EnableDnsSupport: false
    VpcGatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties: 
            InternetGatewayId: !Ref InternetGateway
            VpcId: !Ref PrivateVpc
    RouteTableForPublicSubnet:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId: !Ref PrivateVpc
    InternetRoute:
        Type: AWS::EC2::Route
        Properties:
            DestinationCidrBlock: 0.0.0.0/0
            GatewayId: !Ref InternetGateway
            RouteTableId: !Ref RouteTableForPublicSubnet    
    PublicHeadStoreSubnetAndRouteTableForPublicSubnetAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:          
            RouteTableId: !Ref RouteTableForPublicSubnet
            SubnetId: !Ref PublicHeadStoreSubnet
    # Total addresses: 16
    # Network address: 172.16.0.0
    # Broadcast: 172.16.0.15
    # Netmask: /28
    PublicHeadStoreSubnet:
        Type: AWS::EC2::Subnet
        Properties:
            AvailabilityZone: "us-east-1a"
            CidrBlock: 172.16.0.0/28
            VpcId: !Ref PrivateVpc
    # Total addresses: 16
    # Network address: 172.16.0.16
    # Broadcast: 172.16.0.31
    # Netmask: /28
    PrivateHeadStoreSubnet:
        Type: AWS::EC2::Subnet
        Properties:
            AvailabilityZone: "us-east-1a"
            CidrBlock: 172.16.0.16/28
            VpcId: !Ref PrivateVpc
    # Total addresses: 16
    # Network address: 172.16.0.32
    # Broadcast: 172.16.0.47
    # Netmask: /28
    PublicBranchStoreSubnetAndRouteTableForPublicSubnetAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:          
            RouteTableId: !Ref RouteTableForPublicSubnet
            SubnetId: !Ref PublicBranchStoreSubnet
    PublicBranchStoreSubnet:
        Type: AWS::EC2::Subnet
        Properties:
            AvailabilityZone: "us-east-1b"
            CidrBlock: 172.16.0.32/28
            VpcId: !Ref PrivateVpc
    # Total addresses: 16
    # Network address: 172.16.0.48
    # Broadcast: 172.16.0.64
    # Netmask: /28
    PrivateBranchStoreSubnet:
        Type: AWS::EC2::Subnet
        Properties:
            AvailabilityZone: "us-east-1b"
            CidrBlock: 172.16.0.48/28
            VpcId: !Ref PrivateVpc
    