AWSTemplateFormatVersion: "2010-09-09"

Description: "This is a simple network architecture"

Resources:
    ###################
    # Logical Network #
    ###################
    # Total addresses: 64
    # Network address: 172.16.0.0
    # Broadcast: 172.16.0.64
    # Netmask: /26
    PrivateVpc:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 172.16.0.0/26
            EnableDnsHostnames: false
            EnableDnsSupport: false
    # Total addresses: 16
    # Network address: 172.16.0.0
    # Broadcast: 172.16.0.15
    # Netmask: /28
    PublicSubnet:
        Type: AWS::EC2::Subnet
        Properties:
            AvailabilityZone: "us-east-1a"
            CidrBlock: 172.16.0.0/28
            VpcId: !Ref PrivateVpc
    # Total addresses: 16
    # Network address: 172.16.0.16
    # Broadcast: 172.16.0.31
    # Netmask: /28
    PrivateSubnet0:
        Type: AWS::EC2::Subnet
        Properties:
            AvailabilityZone: "us-east-1b"
            CidrBlock: 172.16.0.16/28
            VpcId: !Ref PrivateVpc
    # Total addresses: 16
    # Network address: 172.16.0.32
    # Broadcast: 172.16.0.47
    # Netmask: /28
    PrivateSubnet1:
        Type: AWS::EC2::Subnet
        Properties:
            AvailabilityZone: "us-east-1c"
            CidrBlock: 172.16.0.32/28
            VpcId: !Ref PrivateVpc
    # Total addresses: 16
    # Network address: 172.16.0.48
    # Broadcast: 172.16.0.64
    # Netmask: /28
    PrivateSubnet2:
        Type: AWS::EC2::Subnet
        Properties:
            AvailabilityZone: "us-east-1d"
            CidrBlock: 172.16.0.48/28
            VpcId: !Ref PrivateVpc
    ################ 
    # Network Acls #
    ################
    MyNetworkAclForPublicSubnet:
        Type: AWS::EC2::NetworkAcl
        Properties:
            VpcId: !Ref PrivateVpc
    InboundRuleForMyNetworkAclForPublicSubnet:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
            CidrBlock: 0.0.0.0/0
            Egress: false
            NetworkAclId: !Ref MyNetworkAclForPublicSubnet
            Protocol: -1
            RuleAction: deny
            RuleNumber: 1
    OutboundForMyNetworkAclForPublicSubnet:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
            CidrBlock: 0.0.0.0/0
            Egress: true
            NetworkAclId: !Ref MyNetworkAclForPublicSubnet
            Protocol: -1
            RuleAction: deny
            RuleNumber: 1    
    PublicSubnetAndMyNetworkAclForPublicSubnetAssociation:
        Type: AWS::EC2::SubnetNetworkAclAssociation
        Properties:
            NetworkAclId: !Ref MyNetworkAclForPublicSubnet
            SubnetId: !Ref PublicSubnet
    MyNetworkAclForPrivateSubnet0:
        Type: AWS::EC2::NetworkAcl
        Properties:
            VpcId: !Ref PrivateVpc
    InboundMyNetworkAclForPrivateSubnet0:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
            CidrBlock: 0.0.0.0/0
            Egress: false
            NetworkAclId: !Ref MyNetworkAclForPrivateSubnet0
            Protocol: -1
            RuleAction: deny
            RuleNumber: 1
    OutboundMyNetworkAclForPrivateSubnet0:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
            CidrBlock: 0.0.0.0/0
            Egress: true
            NetworkAclId: !Ref MyNetworkAclForPrivateSubnet0
            Protocol: -1
            RuleAction: deny
            RuleNumber: 1    
    PrivateSubnetAndMyNetworkAclForPrivateSubnet0Association:
        Type: AWS::EC2::SubnetNetworkAclAssociation
        Properties:
            NetworkAclId: !Ref MyNetworkAclForPrivateSubnet0
            SubnetId: !Ref PrivateSubnet0
    MyNetworkAclForPrivateSubnet1:
        Type: AWS::EC2::NetworkAcl
        Properties:
            VpcId: !Ref PrivateVpc
    InboundMyNetworkAclForPrivateSubnet1:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
            CidrBlock: 0.0.0.0/0
            Egress: false
            NetworkAclId: !Ref MyNetworkAclForPrivateSubnet1
            Protocol: -1
            RuleAction: deny
            RuleNumber: 1
    OutboundMyNetworkAclForPrivateSubnet1:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
            CidrBlock: 0.0.0.0/0
            Egress: true
            NetworkAclId: !Ref MyNetworkAclForPrivateSubnet1
            Protocol: -1
            RuleAction: deny
            RuleNumber: 1    
    PrivateSubnetAndMyNetworkAclForPrivateSubnet1Association:
        Type: AWS::EC2::SubnetNetworkAclAssociation
        Properties:
            NetworkAclId: !Ref MyNetworkAclForPrivateSubnet1
            SubnetId: !Ref PrivateSubnet1
    MyNetworkAclForPrivateSubnet2:
        Type: AWS::EC2::NetworkAcl
        Properties:
            VpcId: !Ref PrivateVpc
    InboundMyNetworkAclForPrivateSubnet2:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
            CidrBlock: 0.0.0.0/0
            Egress: false
            NetworkAclId: !Ref MyNetworkAclForPrivateSubnet2
            Protocol: -1
            RuleAction: deny
            RuleNumber: 1
    OutboundMyNetworkAclForPrivateSubnet2:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
            CidrBlock: 0.0.0.0/0
            Egress: true
            NetworkAclId: !Ref MyNetworkAclForPrivateSubnet2
            Protocol: -1
            RuleAction: deny
            RuleNumber: 1    
    PrivateSubnetAndMyNetworkAclForPrivateSubnet2Association:
        Type: AWS::EC2::SubnetNetworkAclAssociation
        Properties:
            NetworkAclId: !Ref MyNetworkAclForPrivateSubnet2
            SubnetId: !Ref PrivateSubnet2
    ####################
    # Internet Gateway #
    ####################
    InternetGateway:
        Type: AWS::EC2::InternetGateway    
    InternetGatewayAndPrivateVpcAssociation:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties: 
            InternetGatewayId: !Ref InternetGateway
            VpcId: !Ref PrivateVpc
    ################
    # Route Tables #
    ################
    RouteTableForPublicSubnet:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId: !Ref PrivateVpc
    InternetRoute:
        Type: AWS::EC2::Route
        Properties:
            DestinationCidrBlock: 0.0.0.0/0
            GatewayId: !Ref InternetGateway
            RouteTableId: !Ref RouteTableForPublicSubnet
    RouteTableForPublicSubnetAndPublicSubnetAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:          
            RouteTableId: !Ref RouteTableForPublicSubnet
            SubnetId: !Ref PublicSubnet