AWSTemplateFormatVersion: "2010-09-09"

Resources:
  # Ubuntu Server
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-007855ac798b5175e
      InstanceType: t2.micro      
      SecurityGroupIds:
        - !ImportValue simple-network-security-groups-SecurityGroupForWebServerId
      SubnetId: !ImportValue simple-network-subnets-PublicSubnetId
      UserData:
        Fn::Base64:
          |          
          #!/bin/bash
          sudo apt update
          sudo apt upgrate
          sudo snap install amazon-ssm-agent --classic
          sudo snap start amazon-ssm-agent
#TODO: Enable the Session Manger to connect in ec2