AWSTemplateFormatVersion: "2010-09-09"

Resources:
  SecurityGroupForWebServer:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "this security group no allow any traffic"
      GroupName: ForPublicInstance
      VpcId: !ImportValue simple-network-vpc-PrivateVpcId
Outputs:
  SecurityGroupForWebServer:
    Value: !Ref SecurityGroupForWebServer
    Export:
      Name: !Sub "${AWS::StackName}-SecurityGroupForWebServerId"
